---
- hosts: all 
  remote_user: ubuntu
  become: yes
  tasks:
     - name: install nginx
       apt: pkg=nginx state=absent update_cache=yes
       notify: restart nginx
  handlers:
     - name: restart nginx
       service: name=nginx state=restarted enabled=yes

