---
- hosts: all
  remote_user: ubuntu
  become: yes 
  vars:
      password1: "{{ passw }}"
  tasks:
    - name: create user
      user:
           name: vijaya
           update_password: on_create
           state: present
           password: password1
