---

- hosts: web
  #  remote_user: ubuntu
  become: yes
  gather_facts: no
  tasks:
      - name: installing apache
        apt: name=apache2 update_cache=yes state=latest
       # notify: restart the service
      - name: copying index.html
        copy: 
                src: /home/ubuntu/index.html
                dest: /var/www/html/index.html
        notify: restart the service
  handlers:      
      - name: restart the service
        service: name=apache2 state=restarted enabled=yes
