---   #this is to say it's a yaml confiration file

- hosts: all 
  remote_user: ubuntu
  become: yes
  gather_facts: no
  tasks:
     - name: Install apache2 on Hosts
       apt: pkg=apache2 state=present update_cache=yes
       notify: start apache2
    # - name: Restart apache2 Service
    #   service: name=apache2 state=started enabled=yes
  handlers:
     - name: start apache2
       service: name=apache2 state=restarted enabled=yes
