---

- hosts: all
  tasks:
      - name: installing apache ubuntu
        apt: 
           name: apache2 
           update_cache: yes 
           state: present
        become: yes
        when: ansible_facts['os_family'] == "Debian"
        notify: restart apache2
      - name: installing apache redhat
        yum: 
           name: httpd
           update_cache: yes
           state: latest
        become: yes
        when: ansible_os_family == "RedHat"
        notify: restart httpd
  handlers:
      - name: restart apache2
        service: 
            name: apache2 
            state: restarted 
            enabled: yes
        become: yes
      - name: restart httpd
        service:
            name: httpd
            state: restarted
            enabled: yes
        become: yes
