---
- hosts: all
  remote_user: ubuntu
  become: yes
  vars:
     os: "{{ my_os }}"  
  tasks: 
    - name: Install apt Nginx
      apt: pkg=nginx state=present update_cache=true
      when: ansible_os_family == os
      notify: restart nginx
    - name: Install redhat nginx
      yum: pkg=nginx state=present
      when: ansible_os_family == "RedHat"
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=started

