---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: install nginx on Debian
      apt:
         name: nginx
         state: present
         update_cache: yes
      when: ansible_os_family == "Debian"
      notify: restart nginx
    - name: install nginx on RedHat
      yum:
         pkg: nginx
         state: present
         update_cache: yes
      when: ansible_os_family == "RedHat"
      notify: restart nginx
  handlers:
    - name: restart nginx
      service:
          name: nginx
          state: restarted
       
