---
- hosts: all
  tasks:
      - name: java install redhat
        yum:
            name: java-1.8.0-openjdk
            state: present
        become: yes
        when: ansible_facts['os_family'] == "RedHat"
      - name: java install ubuntu
        apt:
            name: openjdk-8-jdk
            state: present
        become: yes
        when: ansible_facts['os_family'] == "Debian"
