---
- hosts: all
  become: yes
  tasks:
    - name: install softwares for ubuntu
      apt: name={{ item }} state=absent
      with_items:
          - elinks
          - git
          - telnet
          - tree
      when: ansible_os_family == "Debian"
    - name: install softwares for RedHat
      yum: name={{ item }} state=present
      with_items:
          - elinks
          - git
          - telnet
      when: ansible_os_family == "RedHat"

