---
- hosts: all
  remote_user: ubuntu
  become: yes
  #become_method: sudo     # This section applicable to whole play
  tasks: 
    - name: Install Nginx
      apt: pkg=nginx state=latest update_cache=true
      remote_user: ubuntu
      become: yes
      #become_method: su   #This is applicable to this particular task
      notify: restart nginx


  handlers:
    - name: restart nginx
      service: name=nginx state=started

