---
- hosts: all
  become: yes
  remote_user: ubuntu
  tasks:
    - name: stop the service
      service:
        name: nginx
        state: stopped
    - name: remove the package
      apt:
        name: nginx
        state: absent
    - name: Ensure uwsgi is removed
      pip:
        name: uwsgi
        state: absent
    - name: clean files created by nginx
      file:
          name: "{{ item }}"
          state: absent
      with_items:
          - /etc/nginx/nginx.conf
          - /usr/share/nginx/html/index.html
          - /etc/nginx/*
