---
- hosts: all
  vars_prompt:
       - name : Name
         prompt: " Enter a Name"
       - name: Age
         promt: "Enter Age"
  tasks:
      - name: print name
        debug:
              msg: " Name is {{ Name }}"

      - name: print age
        debug:
              msg: "{{ Age }}"
