---
- hosts: all
  user : ubuntu
  become: true
  vars: 
      password: "Pavan@123" 
  tasks: 
    - name: create user
      user:
         name: test
         state: absent
         update_password: on_create
         password: password

